### ISSUE TITLE
Bank minerals for a future expansion

### ISSUE THREAD

**Issue by joshtenorio** [joshtenorio/monte-bot#4]
the current method of saving up minerals for a command center works, however it breaks Monte if it is unable to expand to a new location for whatever reason (creep present, enemy army, etc). This means that since a new cc is not being placed, the bot never purchases anything else despite having excess minerals. The current method is also kinda janky.
# Plan
## Following a Build Order
- relatively unchanged
- `Step` from strategy is converted into a `WorkOrder` for internal use
## General Macro Cycle
- update class instance variables `minerals` and `vespene` with current values from the observation interface
- go through our cycle sequentially, and decrement `minerals` and `vespene` accordingly each time we purchase something
## Misc
- will need an `ABILITY_ID` -> `UpgradeID` and `ABILITY_ID` -> `UnitType_ID` specifically for work order
# TODOs
- [ ] Create a struct `WorkOrder` that contains an ability id and unit or upgrade id
- [ ] Create generic `trainUnit` function - goal is to minimize lines of  `gInterface->actions` in the file
- [ ] Conversion functions
- [ ] Will also need to keep track of supply
More TODOs may be added
# References
- `Order.h` from [suvorov-bot](https://github.com/alkurbatov/suvorov-bot/blob/master/src/core/Order.h)
